// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.js

import './globals.css';
import NavBar from '../components/navbar';


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* The NavBar must be placed inside the <body> tag to prevent the 
        "nav cannot be a child of html" hydration error. 
      */}
      <body className="bg-black">
        <NavBar /> 
        {children}
      </body> 
    </html>
  );
}
